### ISSUE TITLE
大佬，可以做一个 青龙面板跑的 项目吗？

### ISSUE THREAD

**Issue by tracy1949** [fletcherjiang/douyu_gift#1]
大佬，可以做一个 青龙面板跑的 项目吗？

**Comment by fletcherjiang** [comment]
回头我看看，提前是你自己搭建好服务器哈

**Comment by tracy1949** [comment]
青龙跑的 日志：
斗鱼 荧光棒
## 开始执行... 2023-02-27 15:17:33

2023-02-27 15:17:33.937 | INFO     | __main__:run:13 - ------登录检查开始------
2023-02-27 15:17:34.493 | INFO     | common.login_check:is_login:17 - Cookie有效,登陆成功
2023-02-27 15:17:34.493 | INFO     | __main__:run:15 - ------登录检查结束------
2023-02-27 15:17:34.494 | INFO     | common.dy_glows:get_glow:25 - ------正在获取荧光棒------

[WDM] - Downloading:   0%|          | 0.00/7.05M [00:00<?, ?B/s]
[WDM] - Downloading: 100%|██████████| 7.05M/7.05M [00:00<00:00, 84.7MB/s]
Traceback (most recent call last):
  File "/ql/data/scripts/douyu_gift/main.py", line 60, in <module>
    run()
  File "/ql/data/scripts/douyu_gift/main.py", line 18, in run
    get_glow()
  File "/ql/data/scripts/douyu_gift/common/dy_glows.py", line 26, in get_glow
    go_room()
  File "/ql/data/scripts/douyu_gift/common/dy_glows.py", line 96, in go_room
    driver = webdriver.Chrome(executable_path=driver_path, options=chrome_options)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 101, in __init__
    self.service.start()
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 88, in start
    self._start_process(self.path)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 195, in _start_process
    self.process = subprocess.Popen(
  File "/usr/local/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/root/.wdm/drivers/chromedriver/linux64/110.0.5481/chromedriver'


## 执行结束... 2023-02-27 15:17:35  耗时 2 秒
